export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_PRODUCT_REVIEWS = 'SET_PRODUCT_REVIEWS';
export const SET_PAGINATION = 'SET_PAGINATION';
export const SET_LOADING = 'SET_LOADING';
export const SET_NEW_PRODUCTS = 'SET_NEW_PRODUCTS';
export const SET_FOUND_PRODUCTS = 'SET_FOUND_PRODUCTS';
export const SET_ATTRIBUTES = 'SET_ATTRIBUTES';
export const SET_FILTERED = 'SET_FILTERED';
export const SET_FILTERED_PAGINATION = 'SET_FILTERED_PAGINATION';
export const SET_RECENTLY_WATCHED = 'SET_RECENTLY_WATCHED';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_WIDGET_PRODUCTS = 'SET_WIDGET_PRODUCTS';
export const SET_ERROR = 'SET_ERROR';

export default {
  SET_PRODUCTS,
  SET_PAGINATION,
  SET_LOADING,
  SET_PRODUCT,
  SET_PRODUCT_REVIEWS,
  SET_NEW_PRODUCTS,
  SET_FOUND_PRODUCTS,
  SET_ATTRIBUTES,
  SET_FILTERED,
  SET_FILTERED_PAGINATION,
  SET_RECENTLY_WATCHED,
  SET_SEARCH_QUERY,
  SET_WIDGET_PRODUCTS,
  SET_ERROR,
};
